Murali/practice/practice/Models/customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace practice.Models
{
    [Table("CustomerDetails")]
    public class customer
    {
        
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Sno { get; set; }
        public string CustomerName { get; set; }
        public string Phonenumber { get; set; }
        public int ProductId { get; set; }
    }
}

Murali/practice/practice/Controllers/customersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using practice.Data;
using practice.Models;
using X.PagedList;



namespace practice.Controllers
{
    public class customersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public customersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.customer.ToListAsync());
        }
        // paging in mvc

        public async Task<IActionResult> Paging(int? page, int? pagesize)
        {
            if (!page.HasValue)
            {
                page = 1;
            }

            if (!pagesize.HasValue)
            {
                pagesize = 5;
            }

            var data = await _context.customer.ToPagedListAsync(page.Value, pagesize.Value);
            return View(data);
        }

        // GET: customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.customer
                .FirstOrDefaultAsync(m => m.Sno == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Sno,CustomerName,Phonenumber,ProductId")] customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.customer.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Sno,CustomerName,Phonenumber,ProductId")] customer customer)
        {
            if (id != customer.Sno)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!customerExists(customer.Sno))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.customer
                .FirstOrDefaultAsync(m => m.Sno == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.customer.FindAsync(id);
            _context.customer.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool customerExists(int id)
        {
            return _context.customer.Any(e => e.Sno == id);
        }
    }
}

Murali/practice/practice/Views/customers/Create.cshtml
@model practice.Models.customer

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phonenumber" class="control-label"></label>
                <input asp-for="Phonenumber" class="form-control" />
                <span asp-validation-for="Phonenumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Murali/practice/practice/Views/customers/Delete.cshtml
@model practice.Models.customer

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phonenumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phonenumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Sno" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Murali/practice/practice/Views/customers/Details.cshtml
@model practice.Models.customer

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phonenumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phonenumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Sno">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Murali/practice/practice/Views/customers/Edit.cshtml
@model practice.Models.customer

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Sno" />
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phonenumber" class="control-label"></label>
                <input asp-for="Phonenumber" class="form-control" />
                <span asp-validation-for="Phonenumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Murali/practice/practice/Views/customers/Index.cshtml
@model IEnumerable<practice.Models.customer>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phonenumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phonenumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Sno">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Sno">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Sno">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Murali/practice/practice/Views/customers/Paging.cshtml
@model IEnumerable<practice.Models.customer>
@using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "Paging";
    // Layout = "~/Views/Shared/_Layout.cshtml";
    var pageNumber = ViewContext.HttpContext.Request.Query["page"];
    var pageSize = ViewContext.HttpContext.Request.Query["pagesize"];
    if (string.IsNullOrEmpty(pageSize))
    {
        pageSize = "5";
    }

    if (string.IsNullOrEmpty(pageNumber))
    {
        pageNumber = "1";
    }
}

<h1>Paging</h1>

<link href="~/css/IPagedList.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-6">
        <p>
            <a asp-action="Create">Create New</a>
        </p>
    </div>
    <div class="col-md-3">
        <label class="mr-2 mt-2 text-info small"> Page number: @pageNumber | @Model.Count() records</label>
    </div>
    <div class="col-md-3 text-right">
        <div class="form-group form-inline">
            <label class="mr-2">Page Size: </label>
            <select name="PageSize" id="PageSize" class="form-control">
                @for (var i = 1; i <= 10; i++)
                {
                    <option value="@(i*5)">@(i*5)</option>
                }
            </select>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phonenumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phonenumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Sno">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Sno">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Sno">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    @Html.PagedListPager(Model, page => Url.Action("Index", "customers", new { page }) + "&pagesize=" + pageSize,
        X.PagedList.Web.Common.PagedListRenderOptionsBase.ClassicPlusFirstAndLast)
</div>

<script>
    $(function () {

        // set default value for Page size dropdown
        var pageSizeJ = '@pageSize';
        if (pageSizeJ.length > 0) {
            $("#PageSize").val(pageSizeJ);
        }

        // fire on pageSize change
        $("#PageSize").on("change", function () {
            window.location.href = '/customers/Paging?page=@pageNumber&pagesize=' + this.value;
        });
    });
</script>